### ISSUE TITLE
Failed to access VVO StopFinder

### ISSUE THREAD

**Issue by horror-vacui** [kiliankoe/dvbpy#17]
Something seems to be changed on the server side. :(
```
>>> import dvb
>>> dvb.find('zellesch')
Failed to access VVO StopFinder. Request Exception ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by horror-vacui** [comment]
Someting is different now

```
>>> import dvb
>>> dvb.find('zellesch', eduroam=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/dvb/dvb.py", line 206, in find
    find_return_results(points['point'])
  File "/usr/lib/python3.9/site-packages/dvb/dvb.py", line 219, in find_return_results
    'city': stop['posttown'],
KeyError: 'posttown'
>>> dvb.find('zellesch')
Failed to access VVO StopFinder. Request Exception ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
