### ISSUE TITLE
catch Value error if no int is returned

### ISSUE THREAD

**Issue by h4llow3En** [kiliankoe/dvbpy#7]
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/dvb-1.0-py3.5.egg/dvb/dvb.py", line 37, in monitor
  File "/usr/local/lib/python3.5/site-packages/dvb-1.0-py3.5.egg/dvb/dvb.py", line 37, in <listcomp>
ValueError: invalid literal for int() with base 10: ''
```

**Comment by kiliankoe** [comment]
Argh. I'm guessing this happens when a bus leaves "now". Good thing we don't have tests here, 'cause they should've caught this :D
